// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int32
	Username       string
	HashedPassword string
	SessionToken   pgtype.Text
	CsrfToken      pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
