// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, hashed_password
) VALUES (
  $1, $2
)
RETURNING id, username, hashed_password, session_token, csrf_token, created_at, updated_at
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, session_token, csrf_token, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT id, username, hashed_password, session_token, csrf_token, created_at, updated_at FROM users
WHERE session_token = $1
LIMIT 1
`

func (q *Queries) GetUserBySessionToken(ctx context.Context, sessionToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTokensLogin = `-- name: UpdateUserTokensLogin :exec
UPDATE users
SET session_token = $1,
    csrf_token = $2
WHERE username = $3
`

type UpdateUserTokensLoginParams struct {
	SessionToken pgtype.Text
	CsrfToken    pgtype.Text
	Username     string
}

func (q *Queries) UpdateUserTokensLogin(ctx context.Context, arg UpdateUserTokensLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserTokensLogin, arg.SessionToken, arg.CsrfToken, arg.Username)
	return err
}

const updateUserTokensLogout = `-- name: UpdateUserTokensLogout :exec
UPDATE users
SET session_token = NULL,
    csrf_token = NULL
WHERE session_token = $1 AND csrf_token = $2
`

type UpdateUserTokensLogoutParams struct {
	SessionToken pgtype.Text
	CsrfToken    pgtype.Text
}

func (q *Queries) UpdateUserTokensLogout(ctx context.Context, arg UpdateUserTokensLogoutParams) error {
	_, err := q.db.Exec(ctx, updateUserTokensLogout, arg.SessionToken, arg.CsrfToken)
	return err
}
