// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package filesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID           int32
	Username     string
	FileName     string
	FileCategory pgtype.Text
}
