// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.files.sql

package filesdb

import (
	"context"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFiles = `-- name: GetFiles :many
SELECT id, username, file_name, file_category FROM files
WHERE username = $1
`

func (q *Queries) GetFiles(ctx context.Context, username string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFiles, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FileName,
			&i.FileCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
