// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package rulesdb

type Rule struct {
	ID              int32
	Username        string
	RuleName        string
	RuleType        string
	RuleDescription string
}
