// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.rules.sql

package rulesdb

import (
	"context"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
  username, rule_name, rule_type, rule_description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, username, rule_name, rule_type, rule_description
`

type CreateRuleParams struct {
	Username        string
	RuleName        string
	RuleType        string
	RuleDescription string
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.Username,
		arg.RuleName,
		arg.RuleType,
		arg.RuleDescription,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RuleName,
		&i.RuleType,
		&i.RuleDescription,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules
WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const getRules = `-- name: GetRules :many
SELECT id, username, rule_name, rule_type, rule_description FROM rules
WHERE username = $1
`

func (q *Queries) GetRules(ctx context.Context, username string) ([]Rule, error) {
	rows, err := q.db.Query(ctx, getRules, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.RuleName,
			&i.RuleType,
			&i.RuleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules
SET rule_type = $1,
    rule_description = $2
WHERE username = $3 AND rule_name = $4
`

type UpdateRuleParams struct {
	RuleType        string
	RuleDescription string
	Username        string
	RuleName        string
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.Exec(ctx, updateRule,
		arg.RuleType,
		arg.RuleDescription,
		arg.Username,
		arg.RuleName,
	)
	return err
}
