# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic


class Rule(pydantic.BaseModel):
    id: int
    username: str
    rule_name: str
    rule_type: str
    rule_description: str
