# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.rules.sql
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from study_llama.rulesdb import models


GET_RULES = """-- name: get_rules \\:many
SELECT id, username, rule_name, rule_type, rule_description FROM rules
WHERE username = :p1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_rules(self, *, username: str) -> AsyncIterator[models.Rule]:
        result = await self._conn.stream(sqlalchemy.text(GET_RULES), {"p1": username})
        async for row in result:
            yield models.Rule(
                id=row[0],
                username=row[1],
                rule_name=row[2],
                rule_type=row[3],
                rule_description=row[4],
            )
