# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Optional


class File(pydantic.BaseModel):
    id: int
    username: str
    file_name: str
    file_category: Optional[str]
