# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.files.sql
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from study_llama.filesdb import models


CREATE_FILE = """-- name: create_file \\:one
INSERT INTO files (
  username, file_name, file_category
) VALUES (
  :p1, :p2, :p3
)
RETURNING id, username, file_name, file_category
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_file(self, *, username: str, file_name: str, file_category: Optional[str]) -> Optional[models.File]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_FILE), {"p1": username, "p2": file_name, "p3": file_category})).first()
        if row is None:
            return None
        return models.File(
            id=row[0],
            username=row[1],
            file_name=row[2],
            file_category=row[3],
        )
